### ISSUE TITLE
Casino Location

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Gambling#1]
A new casino location to showcase various games of chance added by this mod. What are some of the finer details for this goal?

Casino Details
- [x] An entrance requirement such as an attribute or caps check.
- [ ] An alternate entrance quest for players' who cannot pass checks.
- [ ] Casino patron NPCs.
- [ ] Casino bartender NPC.
- [ ] Casino guard NPCs.
- [x] Casino dealer NPC.
- [ ] Casino pit boss NPC.
- [ ] Casino flavor quest.

**Comment by TheWhiteCollarPlayers** [comment]
The current plan is to "renovate" the inside of an unused vanilla building just outside of the Goodneighbor entrance (CK exterior cell name: GoodneighborExt03). The player will have to pass either a Charisma, Strength, or credit check (like in FNV) to enter the building. The "inside" of the building is a reused cell of the Concord Speakeasy which is currently WIP, but nearly all aspects except for the main construction are being redone to accommodate the "casino". Specifically, the basement of the interior will be the Blackjack table is located, there are several other rooms which will remain empty with clutter leaving the option to add more game tables to various areas of the interior. The cell will also contain completely custom and handmade "Patrons" as well as a bartender and a guard, and a pit boss who oversees the casino which leaves possibilities for quest expansion. One potential idea is to have a "Bankrupt Gambler" inside Goodneighbor itself that the player can talk to learn about the unmarked casino and potentially perform a quest to get inside (possibly rough em up because the boss is sick of his casino debt?). I am open to suggestions and ideas for quests and cell designs.

**Comment by TheWhiteCollarPlayers** [comment]
Currently ceasing work on this particular idea as it is not needed for a first playable build. Reflagging as an enhancement.

**Comment by Scrivener07** [comment]
Reflagging as wontfix because this is still a top level feature but we wont be doing anything about it. An enhancement is something that improves a top level feature.

**Comment by Scrivener07** [comment]
This feature currently edits the following vanilla cell: "GoodneighborExt03".

**Comment by Scrivener07** [comment]
Filed issue #14 for the introductory quest line.

**Comment by TheWhiteCollarPlayers** [comment]
Should we close this since we have #14 also per our discussion on Discord?

**Comment by Scrivener07** [comment]
Yes. To recap, we are dropping the casino location feature. We would rather focus on creating more mini-games that are really well integrated into the existing world. At some point we can encourage authors to make their own standalone casinos that use the gambling mod as a framework of sorts. If we want to revisit this and create a casino then reopen the existing issue.
